Make redis and fakeredis optional dependencies
developmentseed/titiler-xarray pull request #57
Opened 2024-04-23 07:46 UTC by emileten

Partially addresses package size issue for lambda : https://github.com/developmentseed/titiler-xarray/issues/56

2024-04-23 08:27 UTC, vincentsarago requested changes
to avoid having exception raised we should do something like https://github.com/developmentseed/cogeo-mosaic/blob/main/cogeo_mosaic/backends/az.py#L17-L24 in
https://github.com/developmentseed/titiler-xarray/blob/dev/titiler/xarray/redis_pool.py#L4-L5

and then https://github.com/developmentseed/cogeo-mosaic/blob/main/cogeo_mosaic/backends/az.py#L40-L43 in the class methods

2024-04-23 08:34 UTC, emileten commented
Sure @vincentsarago I'll make that change in a bit. Also changing accordingly the infra code, will ping you. Thanks !

2024-04-26 10:51 UTC, vincentsarago commented on infrastructure/aws/cdk/app.py
> +            )
can we move this block up, so we don't have 2 `settings.enable_cache`

2024-04-26 10:52 UTC, vincentsarago approved these changes

2024-04-26 10:53 UTC, vincentsarago commented on infrastructure/aws/cdk/app.py
> +            )
not-mandatory if you want to merge

2024-06-21 10:41 UTC, vincentsarago commented
@emileten do we have anything to do here before merging?

2025-01-09 18:50 UTC, abarciauskas-bgse commented
I'm going to close this as stale

2025-01-09 18:50 UTC, closed without merging